cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'darksky-weather'
brew 'direnv'
brew 'doctl'
brew 'coreutils'
brew 'go'
brew 'httpie'
brew 'jq'
brew 'mas'
brew 'mycli'
brew 'mysql'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'pgcli'
brew 'protobuf'
brew 'pyenv'
brew 'unrar'
brew 'tldr'
brew 'tmux'
brew 'wget'

cask '1password'
cask 'alfred'
cask 'atom'
cask 'boostnote'
cask 'dropbox'
cask 'docker'
cask 'firefox'
cask 'gitter'
cask 'google-chrome'
cask 'iterm2'
cask 'minikube'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'tunnelbear'
cask 'tunnelblick'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'zoomus'
