cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'doctl'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'jq'
brew 'mysql'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'postgresql'
brew 'pyenv'
brew 'unrar'
brew 'wget'

cask '1password'
cask 'alfred'
cask 'atom'
cask 'dropbox'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'rambox'
cask 'spotify'
cask 'steam'
cask 'tunnelbear'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'zoomus'
